### ISSUE TITLE
observeCharacter immediately calls cleanup

### ISSUE THREAD

**Issue by Blizzero** [Sleitnick/RbxObservers#2]
`observeCharacter` is expected to trigger its callback when a new character is added, and then trigger the provided cleanup function (if any) on the character's removal. 

In testing, the cleanup is called immediately after the callback, despite the character not being removed. This makes this observer currently unusable.

**Comment by Sleitnick** [comment]
Looks like I missed this because it works properly with `workspace.SignalBehavior` set to `Deferred`. In Immediate mode, it does not work as expected. I'll investigate and push a fix.
